version: '3.8'
services:
  moives:
    image: gopinaidu123/paymoives:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: gopinaidu123/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: gopinaidu123/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: gopinaidu123/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
